### ISSUE TITLE
New glyphs needed

### ISSUE THREAD

**Issue by JBrase** [silnrsi/script-miao#12]
MH: New glyphs needed for UBS projects. 10 glyphs for Bai Yi
(from email 2015-05-06)

**Comment by jvgaultney** [comment]
We need some spec for these (glyph name, encoding if any), and some idea of what they look like.

**Comment by mhosken** [comment]
Glyphs and what they are variants of.

![bai-yi_variants_small](https://cloud.githubusercontent.com/assets/5687149/12779168/259b8fc8-ca99-11e5-97e1-1910077e591e.jpg)

**Comment by mhosken** [comment]
On an initial visual inspection, and more to say that there is more thinking required, I propose what they say as 16F01 should be 16F02, and 16F59 should be 16F5D. There's lots of confusion in my mind as to which sets of glyph variants actually make up one alphabet. Many alphabet charts show multiple variants in the same chart.

Any chance someone can write out a complete minimal alphabet chart for Bai Yi? All the consonants and vowels (no vowel sequences needed), and what they want them to look like. With no variants, but a complete list.

**Comment by jvgaultney** [comment]
I've added the needed glyph slots and designed all but two of them. Here is a list of the new glyphs and the temporary glyph names I have given them. The codes here are the ones in the photo, and are used only for reference:

Consonants:
16F01 (MH suggests 16F02) = u16F01.ycltmp
16F0B = u16F0B.ycltmp
16F38 = u16F38.ycltmp
16F0F = u16F0F.ycltmp
16F33 (not added - already exists in font as u16F33.hmd, u16F33.ycl)

Vowels:
16F61 = u16F61.ycltmp
16F6A = u16F6A.ycltmp
16F59 (MH suggests 16F5D) = u16F59.ycltmp  [still incorrect form]
16F5C = u16F5C.ycltmp  [still incorrect form]
16F73 (not added - already exists in font as u16F5B.ycl, with variants in u16F5B.Aycl, u16F5B.Bycl, u16F5B.Fycl, though their shapes are really ugly)

I have _not_ given these encodings yet in FontForge, nor have I added them to the language-specific .cfg files in /source. Nor have I adjusted the anchors/APs.

**Comment by jvgaultney** [comment]
I've now completed initial designs for u16F59.ycltmp and u16F5C.ycltmp

**Comment by jvgaultney** [comment]
.ycltmp now changed to .ygptmp

**Comment by jvgaultney** [comment]
The latest Unicode proposal addressed these glyphs but with different encodings. All glyphs now added and encoded according to latest proposal.
