### ISSUE TITLE
Glyph shape for U+16F33

### ISSUE THREAD

**Issue by JBrase** [silnrsi/script-miao#13]
Glyph shape for U+16F33 is not right.  It should look like that in Miao Unicode, i.e., the tail is curved but doesn't have a hook.  This is confirmed by the A-Hmao group.

(from email 2015-05-06)

**Comment by jvgaultney** [comment]
I'm confused - The Unicode book shows U+16F33 with a hook. The only difference between what we have now and the book is the size of the hook. So how is it supposed to look? An image, such as a small scan or photograph from a book would be helpful.

**Comment by cheuk879** [comment]
On 2016-02-03 04:31, Victor Gaultney wrote:

> I'm confused - The Unicode book shows U+16F33 with a hook. The only 
> difference between what we have now and the book is the size of the 
> hook. So how is it supposed to look? An image, such as a small scan or 
> photograph from a book would be helpful.

It should look like that in Miao Unicode 
http://phjamr.github.io/miao.html#input : in the initials table, row 
4, 4th char ('sha') from the right.

**Comment by jvgaultney** [comment]
We already have that shape in the font, and it is used when producing the HMD, LPO and YCL versions of the font. Should that also be the default form for the YIG and YWQ?

**Comment by jvgaultney** [comment]
And what about the HMDD and HMDN? And what should the default (non-language-specific) version have?

**Comment by jvgaultney** [comment]
Default changed
