### ISSUE TITLE
Wart needs to be bigger

### ISSUE THREAD

**Issue by JBrase** [silnrsi/script-miao#2]
MH: How much bigger? As big as the internal loops. E.g. in 16F15.  should the eye and the wart be the same size? 

AC: Yes, the diameter should at least be that long.  The vowel /o/ (16F59) is another good comparison

(email from AC, 2015-05-06)

**Comment by jvgaultney** [comment]
How is this for size? The first three are the old size, then second are the proposed new. I haven't pushed these changes yet - this is just a test of size before I do all the glyphs. Does it look right?
![image](https://cloud.githubusercontent.com/assets/4226750/12904369/140b622e-cec7-11e5-8d7c-c406faf9283b.png)

**Comment by cheuk879** [comment]
team says it looks good.  thx!

**Comment by jvgaultney** [comment]
Made all warts larger according to test above
