### ISSUE TITLE
Update glyphs for 16F2C to 16F32 - Unicode 9

### ISSUE THREAD

**Issue by kienwt** [silnrsi/script-miao#23]
Glyphs for 16F2C to 16F32 need to be updated to match Unicode 9.

http://unicode.org/errata/miao-glyph-erratum-16f2c-16f32.jpg

**Comment by jvgaultney** [comment]
I think I've fixed this in the Fontforge file, but I can't explain the hundreds of changes to the .sfd. I tried to be careful to not mess up the OT features. I don't think any OT code changes were needed anyway, as all the glyphs are normal base glyphs and would behave normally I think. There are no new glyphs nor any deletions.
